name: Repo Dispatcher

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Compile Target(Leave blank to compile all supported targets)'
        required: false
      ccache:
        description: 'Disable ccache(Input 1 to disabled)'
        required: false
      clean:
        description: 'Clean toolchain cache(Input 1 to enabled)'
        required: false
      ssh:
        description: 'SSH connection to Actions(Input 1 to enabled)'
        required: false
      cancel:
        description: 'Input 1 to Cancel Running Project'
        required: false
      delete:
        description: 'Input 1 to Delete Workflow Runs'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Running Wrkflows
      uses: styfle/cancel-workflow-action@main
      if: github.event.inputs.cancel=='1'
      with:
        ignore_sha: true
        workflow_id: ${{secrets.WORK_ID}}
        access_token: ${{github.token}}

    - name: Delete Workflow Runs
      uses: wyHFudrMhFKwpNpQEfxdckmMqnp54Ww9/delete-workflow-runs@main
      with:
        retain_min: 0
        keep_minimum_runs: 0

    - name: Trigger Compile
      env:
        REPO_TOKEN: ${{secrets.REPO_TOKEN}}
      run: |
        [ "${{github.event.inputs.cancel}}" = 1 ] && echo "Cancel Running Project!" && exit 0
        [ "${{github.event.inputs.delete}}" = 1 ] && echo "Delete Workflow Runs!" && exit 0
        A=$(curl -LfsH "Authorization: token $REPO_TOKEN" https://github.com/${{github.repository}}/raw/master/README.md | grep Platform | cut -d: -f2)
        [ -z "${{github.event.inputs.target}}" ] && B=$A || B="${{github.event.inputs.target}}";B=${B^^}
        for i in $B;do
            if ! echo $A | grep -q $i;then
                echo "$i:Not support!";exit 1
            fi
        done
        [ "${{github.event.inputs.ccache}}" = 1 ] && C=false || C=true
        [ "${{github.event.inputs.clean}}" = 1 ] && D=true || D=false
        [ "${{github.event.inputs.ssh}}" = 1 ] && E=true || E=false
        for i in $B;do
            curl -Lfs \
            -X POST https://api.github.com/repos/${{github.repository}}/dispatches \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $REPO_TOKEN" \
            -d "{\"event_type\": \"$i\",\"client_payload\": {\"target\":\"$i\",\"ccache\":$C,\"clean\":$D,\"ssh\":$E}}" && echo "啟動$i編譯成功!" || echo "啟動$i編譯失敗!"
        done
